[default.tls]
key = "privkey.pem"
certs = "fullchain.pem"

[default]
address = "::"
limits = { form = "10 MiB", json = "1 MiB" }
port = 443

[debug]
address = "127.0.0.1"
port = 8000

[debug.tls]
key = "privatekey.pem"
certs = "certificate.pem"